config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin_console', as: 'rails_admin'
  devise_for :admins
  devise_for :users, controllers: {registrations: "registrations"}

  root to: "welcome#index"

  resources :subscribers
  resources :products

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable,
         :rememberable, :trackable, :validatable
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, :presence => true
  validates :description, :presence => true
  validates :month, :presence => true
  has_attached_file :image, :styles => { :medium => "450x450#", :thumb => "250x250#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/



end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ActionController::Base
  layout "application"
 def index
 	@products = Product.all
 end

 def show
 	@product = Product.find(params[:id])
 end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
      if @product.save

         redirect_to products_path
      else
        render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)

      redirect_to product_path
    else
    	render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end


  private
  def product_params
    params.require(:product).permit(:name, :month, :description, :image)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    '/subscribers/new'
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
before_filter :authenticate_user!
def new

end

def update

#gets the credit card details submitted in the form
    token = params[:stripeToken]

    #create a customer
    customer = Stripe::Customer.create(
      card: token,
      plan: 1234,
      email: current_user.email
    )

    current_user.subscribed = true
    current_user.stripeid = customer.id
    current_user.save


    redirect_to products_path, notice: "You have sucessfully subscribed! Now go visit the DoomBox Launchpage at: http://doombox.launchrock.com"



  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ActionController::Base
 layout "application"

 def index
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>These errors need fixed:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li class="alert"><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Doombox</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">DoomBox</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
          <ul class="nav navbar-nav">
            <li><%= link_to "Products", products_path %></li>
            <li><a href="http://doombox.launchrock.com/" target="blank">Visit Launchpage!</a></li>
            <li class="social"><a href="https://plus.google.com/explore/NUCLEARWAR" target="blank"><%= image_tag "google.png"%></a></li>
            <li class="social"><a href="https://www.facebook.com/page.Zombies" target="blank"><%= image_tag "fb.png"%></a></li>
            <li class="social"><a href="https://www.youtube.com/watch?v=p2H5YVfZVFw" target="blank"><%= image_tag "stumble.png"%></a></li>
            <li class="social"><a href="https://twitter.com/officialdoombox" target="blank"><%= image_tag "twitter.png"%></a></li>
          </ul>


          <ul class="nav navbar-nav navbar-right">
            <% if current_user == nil && current_admin == nil%>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <li><%= link_to "Sign In", new_user_session_path %></li>
              <li><%= link_to "Admin", new_admin_session_path %></li>
            <% end %>
            <% if current_user %>
              <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
              <li><%= link_to 'Edit', edit_user_registration_path %></li>
            <% end %>
            <% if current_admin %>
              <li><%= link_to "Console", 'admin_console_path' %></li>
              <li><%= link_to 'Sign Out', destroy_admin_session_path, method: :delete %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
    <%= flash[:notice] %>
    <%= flash[:alert] %>

    <%= yield %>
  </div>

  </body>
</html>

app/views/products/_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= simple_form_for @product do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :month %>
  <%= f.submit class: "btn btn-default" %>
<% end %>

app/views/products/edit.html.erb
<h1 class="form-titles">Edit Product</h1>

<%= render "form" %>

app/views/products/index.html.erb
<div class="container">

	<div class="jumbotron">
		<div class="col-md-10 headline_doom">
			<h4><span class="doom_text">DoomBox</span> is your answer to the impending apocalypse. Each month you will receive invaluable advice and supplies to survive a variety of disasters. Subscribe to receive your <span class="doom_text">DoomBox</span> today.</h4>
		</div>
		<div class="col-md-2 subscribe_btn">
			<%= link_to "Subscribe", new_subscriber_path, class: "btn btn-danger" %>
		</div>
	</div>

	<div class="products">
		<ul class="row">
		<% @products.each  do |product| %>
		  <li class="col-lg-3">
		  	<p><%= link_to product.month, product_path(product) %></p>
		    <a class="img-responsive center-block"><%= image_tag product.image.url(:thumb) %></a>
		    <p class="name"><%= link_to product.name, product_path(product) %></p>
		  </li>
		<% end %>
		</ul>

	<% if current_admin %>
		<button class="btn btn-primary"><%= link_to 'Add a Product', new_product_path  %></button>
	<% end %>

	</div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-body">
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

app/views/products/new.html.erb
<h1 class="form-titles">Add a Product</h1>

<%= render "form" %>

app/views/products/show.html.erb
<div class="row">
  <h1 class="headline"><%= @product.name %></h1>
  <hr>

  <div class="col-lg-6" id="product-left">
    <div class="show-img img-responsive"><%= image_tag @product.image.url(:medium) %></div>
  </div>

<div class="col-lg-6" id="product-right">
  <div class="well">
    <h3 class="month">-<%= @product.month %>-</h3>
    <h3 class="content-headline"><small>This</small> DoomBox <small>contains:</small></h3>
      <ul class="content-list">
        <% @product.contents.each do |key, value| %>
        <li><%= key %><%= value %></li>
        <% end %>
      </ul>

    <h3 class="description"><%= @product.description %></h3>

    <div class="text-center">
      <button class="btn btn-danger"> <%= link_to "Sign Up Now!", new_subscriber_path %></button>
      <p class="call-to-action">Get this box by joining the monthly club! Don't die like your neighbors!</p>
    </div>
        <% if current_admin %>
        <hr>
          <button class="btn btn-primary"><%= link_to "Edit", edit_product_path(@product) %></button>
          <button class="btn btn-primary"><%= link_to "Delete", product_path(@product),
                                                      method: :delete,
                                                      data: {confirm: "Are you sure?"} %></button>
       <% end %>
    </div>
   </div>
</div>

app/views/subscribers/_form.html.erb
<%= form_tag subscriber_path(1), method: :put do %>


<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="4900"></script><span> $49 per month, you can cancel at any time (at your own risk).</span>
<% end %> 

app/views/subscribers/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3 panel panel-default form-style">
            <div class="panel-body">
                <h2>Final Signup Step</h2>

                <%= render 'form' %>
            </div>
        </div>
    </div>
</div>

app/views/welcome/index.html.erb
<div class="row">

<div class="img-jumbo">
<%= image_tag("http://i.imgur.com/VnCBS44.jpg") %>
</div>
  <div class="jumbotrony">
    <h1 class="welcome-header">Doom Box</h1>
    <p>You sign up. We save your life. </p>
    <p class="btn btn-danger btn-lg"><%= link_to "Learn more", products_path %></p>
  </div>

<div>